### ISSUE TITLE
plot merge gives error

### ISSUE THREAD

**Issue by arriej** [IntellectualCrafters/PlotSquared#110] opened 2015-01-24 14:42 UTC
hey,

So when i was merging plots it came up with this error on the console: http://paste.ubuntu.com/9851342/
The merge does seem to work fine. 
(I did got rid of the roads before hand because it was the spawn of the world, dont know if that has anything todo with this)

I run  Spigot version: [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-b1e6da1-1092acb (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)

Plugin version: PlotSquared (Version: 2.5.12)

Thanks!

**Comment by boy0001** [comment] 2015-01-24 23:16
Open up your "settings.yml" for plotsquared and disable "worldguard".

**Comment by boy0001** [comment] 2015-01-25 00:17
duplicate of #79 - this ticket will be merged.

**Closed by boy0001** 2015-01-25 00:17 UTC
Labels: bug
