### ISSUE TITLE
Pistons can move plot borders

### ISSUE THREAD

**Issue by dextonanderson** [IntellectualCrafters/PlotSquared#171] opened 2015-03-06 00:40 UTC
Using a piston, you can move and change plot borders. This can also affect pathways.

**Comment by dextonanderson** [comment] 2015-03-10 03:58
This is still not fixed as of version 2.8.3

**Comment by boy0001** [comment] 2015-03-10 04:41
Still duplicate of #4

**Closed by boy0001** 2015-03-10 04:41 UTC
Labels: duplicate
