### ISSUE TITLE
Conversion Plotme

### ISSUE THREAD

**Issue by BorussiaMG** [IntellectualCrafters/PlotSquared#86] opened 2015-01-09 06:53 UTC
Hi,
I've got this error message.

[07:21:36] [Server thread/INFO]: [0;36;22mPlotMe[0;30;1m->[0;36;22mPlotSquared[0;30;1m: [0;37;22mConversion has started[m
[07:21:36] [Server thread/INFO]: [0;36;22mPlotMe[0;30;1m->[0;36;22mPlotSquared[0;30;1m: [0;37;22mCaching playerdata...[m
[07:21:36] [Server thread/WARN]: [PlotSquared] Task #15 for PlotSquared v2.5.3 generated an exception
java.lang.NoClassDefFoundError: com/worldcretornica/plotme/PlotManager
	at com.intellectualcrafters.plot.database.PlotMeConverter$1.run(PlotMeConverter.java:92) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[craftbukkit.jar:git-Spigot-13716d9-0899683]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [craftbukkit.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:694) [craftbukkit.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [craftbukkit.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [craftbukkit.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [craftbukkit.jar:git-Spigot-13716d9-0899683]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.ClassNotFoundException: com.worldcretornica.plotme.PlotManager
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[?:1.8.0_25]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.8.0_25]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_25]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[?:1.8.0_25]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[craftbukkit.jar:git-Spigot-13716d9-0899683]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[craftbukkit.jar:git-Spigot-13716d9-0899683]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	... 8 more

**Comment by boy0001** [comment] 2015-01-09 07:44
Duplicate of issue #75

Will be fixed soon. If you don't want to wait, please downgrade your version of PlotMe.

**Closed by boy0001** 2015-01-09 07:44 UTC

**Comment by BorussiaMG** [comment] 2015-01-09 19:31
To which version i have to go? Now it's 0.15.2 installed.

**Comment by boy0001** [comment] 2015-01-10 02:34
The problem was that the latest PlotMe forcefully disables PlotSquared if it's detected, which has made updating the converter somewhat difficult.

If you download the latest version of PlotSquared, it should fix the issue with the conversion process.
