### ISSUE TITLE
Plot delete issue

### ISSUE THREAD

**Issue by thu2468** [IntellectualCrafters/PlotSquared#95] opened 2015-01-17 07:30 UTC
When i claim a plot it doesnt delete the plot
[02:29:23 INFO]: thu2468 issued server command: /plot delete
[02:29:23 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'plot' in plugin PlotSquared v2.5.10
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[creativespigot-1.8.jar:git-Spigot-fa7cbf9-42ebec1]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[creativespigot-1.8.jar:git-Spigot-fa7cbf9-42ebec1]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[creativespigot-1.8.jar:git-Spigot-fa7cbf9-42ebec1]
        at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [creativespigot-1.8.jar:git-Spigot-fa7cbf9-42ebec1]
        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [creativespigot-1.8.jar:git-Spigot-fa7cbf9-42ebec1]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [creativespigot-1.8.jar:git-Spigot-fa7cbf9-42ebec1]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [creativespigot-1.8.jar:git-Spigot-fa7cbf9-42ebec1]
        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [creativespigot-1.8.jar:git-Spigot-fa7cbf9-42ebec1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_65]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_65]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [creativespigot-1.8.jar:git-Spigot-fa7cbf9-42ebec1]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [creativespigot-1.8.jar:git-Spigot-fa7cbf9-42ebec1]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [creativespigot-1.8.jar:git-Spigot-fa7cbf9-42ebec1]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [creativespigot-1.8.jar:git-Spigot-fa7cbf9-42ebec1]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
Caused by: java.lang.AbstractMethodError: com.intellectualcrafters.plot.object.PlotManager.clearPlot(Lorg/bukkit/World;Lcom/intellectualcrafters/plot/object/Plot;Z)Z
        at com.intellectualcrafters.plot.util.PlotHelper.clear(PlotHelper.java:708) ~[?:?]
        at com.intellectualcrafters.plot.util.PlotHelper.clear(PlotHelper.java:748) ~[?:?]
        at com.intellectualcrafters.plot.object.Plot.clear(Plot.java:349) ~[?:?]
        at com.intellectualcrafters.plot.commands.Delete.execute(Delete.java:66) ~[?:?]
        at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:184) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[creativespigot-1.8.jar:git-Spigot-fa7cbf9-42ebec1]
        ... 14 more

**Comment by thu2468** [comment] 2015-01-17 07:51
Plot clear also doesnt work

**Comment by boy0001** [comment] 2015-01-17 23:45
Issue with AdvPlots. Are you using the latest version?

If you are up to date, I've lost access to the git repo, so it could be some time until I'm able to update it.

**Comment by thu2468** [comment] 2015-01-18 02:14
Oh ok :/

**Comment by boy0001** [comment] 2015-01-18 20:40
duplicate of #84

**Closed by boy0001** 2015-01-18 20:40 UTC
Labels: bug

**Comment by thu2468** [comment] 2015-01-18 22:19
Is there anyway not to use advplots and keep our current plots with all the nice roads?
