### ISSUE TITLE
/plot home and /plot clear do not teleport to correct position

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualCrafters/PlotSquared#103] opened 2015-01-23 01:51 UTC
As it says in the title, /plot home takes you underground, and /plot delete takes you to the center under bedrock

**Comment by EvilOlaf** [comment] 2015-01-23 17:47
Teleportation to center confirmed but not under the bedrock, just in the center of the plot to delete.

**Comment by boy0001** [comment] 2015-01-23 23:19
It should be fixed in the latest version now, please re-open if not.

**Closed by boy0001** 2015-01-23 23:19 UTC
Labels: bug, high priority

**Comment by PhanaticD** [comment] 2015-01-23 23:22
it is fixed, however plot delete still takes you to the center of the plot, not sure if that is intended or not

**Comment by boy0001** [comment] 2015-01-23 23:36
It's sort of intended. If you are underground while deleting/clearing a plot, it's useful to be teleported to the surface, rather than suffocate. It hasn't been fully implemented, and doesn't currently check if you are underground or not.

**Comment by EvilOlaf** [comment] 2015-01-24 07:51
This behavior is not fully comprehensible  to me. I think it does not mind if you are on the surface or underground or wherever on the plot. You should be always be teleported to the surface when deleting preferably to the sideroad.
