### ISSUE TITLE
[Suggestion] Plot merge generates augmented terrain

### ISSUE THREAD

**Issue by kangarko** [IntellectualCrafters/PlotSquared#243] opened 2015-04-03 12:46 UTC
When I merge two plots with augmented all terrain, the terrain could be generated in the road to prevent sharp edges.

**Comment by boy0001** [comment] 2015-04-03 13:16
duplicate of #214

**Closed by boy0001** 2015-04-03 13:16 UTC

**Comment by kangarko** [comment] 2015-04-03 13:33
Sorry, did not notice. Thanks :)
