### ISSUE TITLE
plot clear does not show the plot being cleared

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualCrafters/PlotSquared#186] opened 2015-03-11 05:29 UTC
looks at screenshot http://gyazo.com/1e117b9a02bddeaeef56b84b89c819de

the whole plot was stone, this is what it looks like after /plot clear

ID 4;85 in 100x100 plot world

**Comment by EvilOlaf** [comment] 2015-03-11 08:31
Propably known issue. Did you try to relog?

**Comment by boy0001** [comment] 2015-03-11 08:54
potential duplicate of #167
Can you verify that a relog does not update the chunks?

**Comment by PhanaticD** [comment] 2015-03-11 11:18
relog does show, maybe make it a config option whether or not to refresh chunks on clear?

**Comment by boy0001** [comment] 2015-03-11 11:52
Well... the issue is that it does refresh the chunks, but because the new chunk has air above the plot, it doesn't send properly. 

Let me explain how it works, as going through it may help me think of a solution. 
 - The world is seperated into regions, each region contains 1024 chunks. 
 - Each chunk is then split into 16 smaller chunks (every 16 y blocks). 
 - Each of these mini-chunks has 4096 blocks.
 - A bulk packet is sent when a client visits a chunk for the first time. These bulk packets don't send mini chunks that only contain air, in order to save on bandwidth.
 - Any modifications after a client can see a chunk usually use single block updates e.g. when a player mines a block. PlotSquared doesn't do this because lets say you clear a 128x128 plot, you could have a max of ~4.2 million block updates which all have a lot of overhead. 
 - Instead we send these bulk chunk updates, but the issue that any mini-chunk that is filled with air will not overwrite existing blocks client side.
 - These chunks packets were not designed to update existing chunks that the client can see.

**Closed** 2015-03-17 07:10 UTC
Labels: bug, duplicate
